### ISSUE TITLE
Add tests for commenting

### ISSUE THREAD

**Issue by oliverroick** [NASA-IMPACT/nasa-apt-frontend#398]
**Context**

As we're building out test coverage across the front-end, we want to add tests from comments. The ticket will add tests to create comments. The following tests should be added:

- Create a comment
- Reply to a comment
- Select a user to mention
- Select curators to mention

**Acceptance criteria**

- [ ] User flow is tested:
  - [ ] Write comment
  - [ ] Submit comment
  - [ ] Updates to UI (toast messages, etc.)
- [ ] POST requests are mocked and tested, ie. the correct payload is sent

**Comment by wrynearson** [comment]
@kamicut FYI (from your work on https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/471)
