### ISSUE TITLE
Add tests for editing algorithm description

### ISSUE THREAD

**Issue by oliverroick** [NASA-IMPACT/nasa-apt-frontend#399]
**Context**

As we're building out test coverage across the front-end, we want to add tests for editing the ATBD. The ticket will add tests to edit the document's algorithm description. The following tests should be added:

- Navigate to the document's edit page
- Enter content into the text fields
  - Add an equation
  - Add an image
  - Add a table
- Save the form

**Acceptance criteria**

- [ ] User flow is tested:
  - [ ] Write comment
  - [ ] Submit comment
  - [ ] Updates to UI (toast messages, etc.)
- [ ] Necessary API calls are mocked
- [ ] POST requests are mocked and tested, ie. the correct payload is sent

**Comment by wrynearson** [comment]
@kamicut FYI (from your work on https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/471)
