### ISSUE TITLE
Dashboard View of Documents is Slow

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#414]
When users look at the dashboard to see documents, it currently takes ~15 for the documents to load. When more documents are added, this will continue to slow down, eventually making APT unusable.

We fixed this issue in SNWG, but I can't find the related PR. I'll keep looking and will update this ticket when I find it. cc @sunu @batpad

**Comment by kamicut** [comment]
@wrynearson I could not reproduce locally, are we talking about the production website? It would be good to test the threshold at which the dashboard becomes perceivably slow to figure out a solution.

**Comment by wrynearson** [comment]
Thanks for testing. We're looking at any instance (local, staging, or prod). Our experience on RGT was that once there were more than ~50 documents, the time to load the curator dashboard was noticeably longer. We can do some internal testing if we'd like to see what happens after 100 or 200 documents

**Comment by sunu** [comment]
From a quick look at the network requests, this looks like an issue with the js bundle size.

On first load, without caching, the js bundle takes almost 15 seconds to load:
![image](https://user-images.githubusercontent.com/1142203/230560468-a37f5989-fbb3-4dd3-bc9a-f4cf264c9477.png)

In comparision, the API call to the backend returns in ~500ms while loading 46 ATBDs as a curator on APT staging
![image](https://user-images.githubusercontent.com/1142203/230560724-936cc2aa-cfe0-4854-8ccf-392f6fe22d40.png)

**Comment by wrynearson** [comment]
Interesting, thanks @sunu. What do you suggest that we do? Maybe @kamicut or @frozenhelium could look into this when you get the chance?

**Comment by wrynearson** [comment]
@kamicut @frozenhelium I'll close this for now. If the issue reappears, then we can investigate. This issue could become more serious when we have more ATBDs in APT.
