### ISSUE TITLE
Missing content in new PDF architecture

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#417]
In testing by @bwbaker1, some content (images, tables, equations) that were present in the view mode were not present in the Document PDF. We think this is related to page breaks.

@frozenhelium is looking into this.

Some screenshots from testing are in [this document](https://docs.google.com/document/d/1WYjpT_zx44gbyx_9IDsylQdowGjSRmViaPnoDoAJY8U/edit).

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH this is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson I am still seeing issues of images/figures not appearing on the PDF. See below.

Editing mode:
![Screen Shot 2023-03-22 at 9 29 53 AM](https://user-images.githubusercontent.com/56319064/226936576-4be4ff03-63d1-4f56-8114-71c338f89113.png)

Viewing mode:
![Screen Shot 2023-03-22 at 9 29 20 AM](https://user-images.githubusercontent.com/56319064/226936634-5d0ce021-a6db-4cd2-9d26-377b8c543e84.png)

PDF:
![Screen Shot 2023-03-22 at 9 29 32 AM](https://user-images.githubusercontent.com/56319064/226936668-0776d0ce-fae2-4146-b074-15553790eb23.png)

**Comment by wrynearson** [comment]
@bwbaker1 can you add @frozenhelium (same preferred APT username) to the document where you have the issue? @frozenhelium was not able to recreate the issue, so it would be nice to see exactly where this missing content occurs.

**Comment by bwbaker1** [comment]
@wrynearson @frozenhelium I added you both to the document "Figure and Equation Test."  It is just a test document, so feel free to change anything you need.

**Comment by wrynearson** [comment]
Thanks @bwbaker1. we'll look into it ASAP

**Comment by frozenhelium** [comment]
@wrynearson I'm looking into it!

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH unfortunately we haven't been able to figure this out. 

@frozenhelium figured out what is happening (when we create the TOC or when we add the heading numbers, the missing content / image is there but shifted to right of the page without any option to scroll, making it not rendered within the standard PDF width), but we don't know why it is happening.

We don't have a good way of knowing how widespread this issue is without having multiple documents where we've identified that content isn't being rendered correctly. Given what has been communicated to users, I would suggest that we continue as planned and deploy the big update to production tomorrow as we think that the most recent PR is an improvement over not updating production. We can communicate that this is a known issue and that we will make this our top priority to fix. We have another rendering approach in mind, but that will take about 0.5-1 sprints to implement.

Please let me know your thoughts.

Hopefully issues like this will be easier to identify with https://github.com/NASA-IMPACT/nasa-apt/issues/659

cc @batpad

**Comment by deborahUAH** [comment]
**We must push with what capability we have.**  @wrynearson This must be fixed asap!   I hope you understand that to me, this is an example of instability.  PDFs are working.... oh wait they're not working right... we don't know why.... so we have to deliver with caveats. NOT good for APT user satisfaction.

**Comment by wrynearson** [comment]
@deborahUAH well understood, I completely agree that this is an example of instability and is not acceptable for users. This is a good example for why we need https://github.com/NASA-IMPACT/nasa-apt/issues/659. This issue was complex because:
1. We thought we had solved for it until @bwbaker1 found the issue still existed
2. We couldn't consistently reproduce it
3. The bug was coming from an external library we were using

I don't mean to list these as excuses – you're right that the end result was still user dissatisfaction and APT instability. 

For me, the takeaways are:
1. https://github.com/NASA-IMPACT/nasa-apt/issues/659 is very important to make sure we're delivering a stable product. This will be top priority for us next sprint.
2. We shouldn't have promised a specific delivery date to users, and instead should consider other was to inform users of changes without pinpointing specific dates or deadlines.
    - It is very tempting when users ask "when will X be ready" to give them a specific date. 
    - However, if anything goes wrong (which it did for several reasons [outlined in the apt-dev channel](https://developmentseed.slack.com/archives/C01MQ3VHG9Y/p1680102625417139)), then it will set us up for failure and dissatisfied users, and we lose their trust.
    - [One suggested approach (point 3 of this blog post)](https://www.mozello.com/blog/things-you-should-never-promise-your-customers#:~:text=3.%20Specific%20product%20launch%20date%20when%20the%20product%20is%20not%20ready%20yet) is to only state when features will be ready at the quarterly level. 
    - If user workflow changes are to be made (e.g. https://github.com/NASA-IMPACT/nasa-apt/issues/608), we can launch those separately once we're sure that the individual feature is ready. We can give them a timeframe (e.g. "in the coming week..." or "by the end of the week..."). That gives us the opportunity to deliver early, gaining trust from users.
    - _I should have flagged this when this deployment date was suggested and before the email went out to users_. I was in the same mindset that we wanted to get this out to users ASAP, which made me not see this risk.

cc @batpad @bwbaker1

**Comment by bwbaker1** [comment]
@wrynearson @batpad @deborahUAH I just tried to test.  The test document from yesterday ("Test March 30") renders correctly now.  All of the content is there.  **However, when I try to edit the document or create a new document, I am NOT able to add an image or import a bibtex file.**  

I am unable to do a thorough test atm but hopefully will have time later this morning.  Therefore, I am not sure if there are other things no longer working.

**Comment by bwbaker1** [comment]
@wrynearson The issue I am having is related to Google Chrome, and the issue happens on both staging and prod.  I tested using Safari and Firefox and everything worked as expected.
