### ISSUE TITLE
Link BibTeX and co-author videos to tooltips in frontend

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#427]
Once https://github.com/NASA-IMPACT/nasa-apt/issues/615 and https://github.com/NASA-IMPACT/nasa-apt/issues/617 are ready, we need to link these videos into tooltips in the edit mode. These links should be displayed in a similar way to how we have them in SNWG.
1. The user hovers over a tooltip
2. The tooltip has text that is hyperlinked
3. Clicking on the hyperlinked text opens `drive.google.com/xxx`, displaying the desired video.

![Image](https://user-images.githubusercontent.com/25919630/226590074-2b4a8f12-5abe-4163-a68d-ed0cda3fdfb6.png)

![Image](https://user-images.githubusercontent.com/25919630/226590173-0261f9fa-a8bd-480f-bac3-2575df606657.png)

For https://github.com/NASA-IMPACT/nasa-apt/issues/615, this should be placed near the `Import from BibTeX file` prompt.

![Image](https://user-images.githubusercontent.com/25919630/226589537-2d015734-a7db-4212-a50d-6cbfba061536.png)

For https://github.com/NASA-IMPACT/nasa-apt/issues/617, this tooltip location is to be determined.

**Comment by wrynearson** [comment]
@deborahUAH @bwbaker1 flagging that https://github.com/NASA-IMPACT/nasa-apt/issues/617 occurs in multiple points in the UI, so I don't know the best place to link this video to. We had discussed the contact section. Thoughts?

**Comment by deborahUAH** [comment]
Text:  Watch BibTeX Import Video here
Link:  @bwbaker1 ?  or @wrynearson   where is video stored ?  what is link?

**Comment by deborahUAH** [comment]
@bwbaker1  please add comment here when updated video is ready for team to link to.

**Comment by bwbaker1** [comment]
@wrynearson The location/text looks good to me.

**Comment by wrynearson** [comment]
@bwbaker1 just following up on this for sprint planning purposes – what's the status of these videos?

**Comment by bwbaker1** [comment]
@wrynearson 

-  [#616 ](https://github.com/orgs/NASA-IMPACT/projects/13/views/1?filterQuery=-no%3Astatus&pane=issue&itemId=17669880#:~:text=Help%20video%3A%20Login%20and%20Create%20a%20New%20ATBD%23616) is ready.
- [#617](https://github.com/orgs/NASA-IMPACT/projects/13/views/1?filterQuery=-no%3Astatus&pane=issue&itemId=17669928#:~:text=Help%20video%3A%20Managing%20Roles%20part%201%20%2D%20How%20to%20add%20collaborators%20and%20change%20lead%20author%23617) is ready.
- [#615](https://github.com/NASA-IMPACT/nasa-apt/issues/615) will be ready S3W1.

**Comment by wrynearson** [comment]
Thanks @bwbaker1. Here's to track what we've implemented (not on staging yet)

- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/615
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/616
- [ ] https://github.com/NASA-IMPACT/nasa-apt/issues/617

**Comment by bwbaker1** [comment]
@wrynearson [#615](https://github.com/NASA-IMPACT/nasa-apt/issues/615#:~:text=Add%20Help%20video%3A-,BibTeX,-import%20%23615) is now ready.

**Comment by wrynearson** [comment]
@bwbaker1 all help videos should be on staging now. Please let me know if we missed any of them!

**Comment by bwbaker1** [comment]
@wrynearson I can see/play [#615](https://github.com/NASA-IMPACT/nasa-apt/issues/615) and [#616](https://github.com/NASA-IMPACT/nasa-apt/issues/616) on staging. 

1. However, when I try to play [#617](https://github.com/NASA-IMPACT/nasa-apt/issues/617), I get the following error:

![Screen Shot 2023-06-16 at 8 07 22 AM](https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/56319064/c0ba7454-a63a-4768-9a93-e00da5d3e2a2)

2. I think we (impact) need to add a still frame to the beginning of [#616](https://github.com/NASA-IMPACT/nasa-apt/issues/616). The first second of the video is a solid white background, so it looks very unappealing. It would be fine if it were a tooltip, but this video is on a main webpage. Do we just need to share with you the new link once we edit the video? 

We will keep this in mind if we create any other videos. Sorry for the inconvenience.

![Screen Shot 2023-06-16 at 8 48 16 AM](https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/56319064/9b933018-f870-4432-b639-99240052758b)

**Comment by wrynearson** [comment]
Hi @bwbaker1, we'll use this link for #617: https://drive.google.com/file/d/1ZObXp0BjxSUWYs4vv6V7q8aRI9rLiseJ/view?usp=sharing.

If you need to make edits to videos, please use the "Manage Versions" feature by right-clicking on the video in Drive. That way, the link stays the same.
