### ISSUE TITLE
Contact section in PDF doesn't update

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#428]
_See https://github.com/NASA-IMPACT/nasa-apt/issues/606#issuecomment-1477975490_

When an author is changed in the contacts section, the change is not reflected in the PDF, even though the change is reflected in the view mode.

## Acceptance Criteria

- [x] Contact section updates propagate to the PDF

**Comment by wrynearson** [comment]
@sunu do you think this is related to PDF caching work you've been working on?

**Comment by wrynearson** [comment]
@bwbaker1 this should be fixed. I haven't had the chance to test it, but I will once it's ready on staging (~15 min). Feel free to test it as well.

**Comment by bwbaker1** [comment]
@wrynearson This looks correct now.  Ready for production.

cc @deborahUAH
