### ISSUE TITLE
ToC shouldn't include contacts, contact names shouldn't be numbered

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#430]
The details of the `contacts` section (i.e., contact names) shouldn't have heading numbers, and shouldn't appear in the ToC. The header for the `contacts` section should still have heading numbers and should appear in the ToC.

**Comment by wrynearson** [comment]
FYI @bwbaker1 and @deborahUAH, we found that the contacts in the `contacts` section were being assigned heading numbers and appeared in the table of contents. We are removing it. Please let me know if this is correct and please re-test once this is on staging. Thanks

**Comment by bwbaker1** [comment]
@wrynearson Agree that each contact should not be assigned heading numbers.  Let us know when this is ready for testing.

**Comment by wrynearson** [comment]
@bwbaker1 this will be on staging in ~15 min and is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson This looks good and is ready for production.
