### ISSUE TITLE
`Journal Details` are not present in Document PDF

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#431]
When authors mark an ATBD for publication, they are presented with several new edit fields. These headers and contents `Journal Details` should not be present in the Document PDF (only the Journal PDF).

One of the new fields, `Key Points`, should be a sub-header of `Journal Details` in the view mode and displayed on the title page of the [Journal PDF](https://docs.google.com/document/d/1T4q56qZrRN5L6MGXA1UJLMgDgS-Fde9Fo4R4bwVQDF8/edit#heading=h.aa2qznm1a6w7), but that will be ticketed elsewhere.

![Image](https://user-images.githubusercontent.com/25919630/226845656-bde6982d-16bc-4226-b951-2a433962dce3.png)

## Acceptance Criteria

- [ ] `Journal Details` section doesn't appear in document PDF

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH please let me know if this is incorrect

**Comment by wrynearson** [comment]
OK thanks @bwbaker1. Since we're working on Document PDF, we'll hide all of the journal details in the Document PDF and then will implement Key Points properly on the Journal PDF

**Comment by wrynearson** [comment]
This will be ready for your review on staging in ~15 minutes. This PR ☝️ only covers the Document PDF work

**Comment by bwbaker1** [comment]
@wrynearson This looks good. The only thing is that the "Plain Language Summary" should not be on the Document PDF (only on the Journal PDF). But it's okay to go ahead and push to production.

cc @deborahUAH

**Comment by deborahUAH** [comment]
Ok to have the plain language summary on the document PDF per a discussion
with Aaron and Anthony last year.
