### ISSUE TITLE
Swap Title Page & ToC Page in Document PDF

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#443]
## Current Behavior

- The table of contents is rendered before the title page for Document PDFs
- There is a page break between the ToC and the title page

## Desired New Behavior

- [x] The title page is rendered before the ToC
- [x] There is a page break between the title page and the ToC (the ToC starts on a new page after the title page)
- [x] There is a page break between the ToC and the body content (the Abstract section starts on a new page after the ToC)

**Comment by wrynearson** [comment]
@deborahUAH please check the desired behavior for this new ticket. In particular, let me know if the abstract should:
1. Start on a new page
2. Should immediately follow the end of the ToC section

Option 2 is less predictable – e.g. if the ToC fills up most of a page but not all, the Abstract header could be on the same page as the ToC but the abstract body could be on another page.

cc @batpad @bwbaker1

**Comment by deborahUAH** [comment]
@wrynearson  yes, abstract should start on a new page.  Order should be:
1) Title page, page break;  
2) TOC, page break;  
3) Abstract, Plain Language Summary (without numbering), page break  
4) Sections 1 - 8 (contacts, currently numbered as ), page break;  
5) References (there needs to be either indentation or a line break between each reference - right now it looks like one large hard to read blob of text.  Also they are double spaced and don't need to be.  Would be great if URLs and DOIs were hyperlinks in the references, but I recognize that may be a tall order)

@bwbaker1  We need to carefully look at the Journal PDF structure as well to make sure it is correct, meets guidelines, and is readable.

**Comment by wrynearson** [comment]
Hi @deborahUAH, thanks for the details. We've implemented your points 1 and 2 which [were the requests we received](https://developmentseed.slack.com/archives/C01MQ3VHG9Y/p1680203876597069) when we deployed this to production. @bwbaker1 could you test for Deborah's points 1 and 2 (the three "Desired Criteria" at the top of this ticket)?

As for points 3-5, we can look into them as separate tickets. These seem like new requests – are they being made now to make sure that we could got out the new PDF architecture in a timely manner? To be clear, we're still talking about the Document PDF, correct?

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH I tested points 1 and 2 (Title page, page break; TOC, page break). These are correct on staging.
