### ISSUE TITLE
`References` section should have clearer separation between entries

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#446]
_See https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/443#issuecomment-1492422214_

## Current Behavior
The `References` section has uniform line spacing.

## Desired Behavior

A few options here. @deborahUAH mentioned we could either:

- [ ] Indent each entry
- [x] Have a line break between entries (and remove current line spacing)

Or, to follow AGU/APA requirements (which would make implementation easier for the `Journal` PDF in the future:
- [x] The reference section follows AGU/APA requirements by having a "hanging indentation" (if an entry goes to a 2nd line, that 2nd line is indented).

**Comment by wrynearson** [comment]
cc: @deborahUAH @batpad @bwbaker1 @kamicut

**Comment by frozenhelium** [comment]
@wrynearson what do you think, option 1 or 2?
### Option 1
![2023-04-04-123510](https://user-images.githubusercontent.com/4931541/229711196-57328b21-fd3b-444b-acc9-8697238dc301.png)

### Option 2
![2023-04-04-123618](https://user-images.githubusercontent.com/4931541/229711256-8808844d-a969-4d2b-bcc3-4d92b6af54c5.png)

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH this is on staging and is ready for your review.

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH References look much better now.   One more tiny thing that needs adjusting - there needs to be a space between each author in the citation.

Current look:


![Image](https://user-images.githubusercontent.com/56319064/229884338-4b7d3f4d-255a-460f-bf0e-01601abc9256.png)

How it should look (note yellow highlights show where spaces are needed):


![Image](https://user-images.githubusercontent.com/56319064/229885183-65a6c73c-56a8-46ae-b40c-8ed91057835b.png)

**Comment by wrynearson** [comment]
Thanks @bwbaker1. I see that we currently don't have spaces between authors on production (in view, edit or PDF modes).

@frozenhelium or @kamicut – is this something you could add or should I make a new ticket?

I think it's related to the `.join()` in lines 119 and 122: https://github.com/NASA-IMPACT/nasa-apt-frontend/blob/69e8d892fb44bf74679baf255d0db51faf1a568f/app/assets/scripts/utils/references.js#L115-L122

**Comment by bwbaker1** [comment]
@wrynearson ^ The added spaces looks good!

**Comment by wrynearson** [comment]
Merged to production with https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/462
