### ISSUE TITLE
Increase time for PDF generation before user is warned the PDF generation failed

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#451]
## Current Behavior

After ~30s, if the document PDF isn't ready, the user is presented with an error saying the PDF generation failed.

Many ATBDs will be long and complex documents, and with our current PDF generation approach, will take longer than ~30s to generate.

## Desired Behavior

- [ ] PDFs can generate for longer than 30s before the user is warned that the PDF generation failed.

**Comment by wrynearson** [comment]
@deborahUAH @bwbaker1 this is updated on staging. Some large ATBDs were not rendering in time, so we gave the user a warning. The PDF rendering was continuing in the background, so if a user retried, they would get the PDF.

We increased the time before a user was given the error message to about ~150s, and changed the error message to say that they should retry.

**Comment by bwbaker1** [comment]
@wrynearson @deborahUAH I tested with this [document](https://nasa-apt.surge.sh/documents/this-is-a-large-document-test/v1.0).  I got the pop-up below on my first download attempt, and then the document downloaded on the next try.  I think we can mark this as ready for deployment. 



![Image](https://user-images.githubusercontent.com/56319064/230196428-c149e872-4a06-4276-8c7d-62ad526b639a.png)

**Comment by wrynearson** [comment]
@bwbaker1 @deborahUAH if you'd prefer for us to further increase the time between PDF generation starts and when we serve an error message, we can do so easily. We're trying to balance delivering timely information with minimizing error messages.

@bwbaker1, if the document you tested is within the normal size range for ATBDs, I'd suggest us increasing this timeout to 4-5 minutes (it's currently at 2.5 min)

**Comment by wrynearson** [comment]
Sounds good, it'll now say "PDF generation in progress." for ~10 seconds, then "Generating the PDF. This may take up to 5 minutes."

<img width="369" alt="image" src="https://user-images.githubusercontent.com/25919630/230385209-f2604ce2-95f3-4113-bdee-a1723ab87295.png">

**Comment by wrynearson** [comment]
Merged to production with https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/462
