### ISSUE TITLE
Bug: New user sign up in APT fails (repeat 4/11/23-4/12/23)

### ISSUE THREAD

**Issue by naomatheus** [NASA-IMPACT/nasa-apt-frontend#461]
### Summary:
Users attempting to sign up for the application are presented with an error message when clicking the "Sign Up" button. They are redirected to an AWS Cognito error page, which displays a 404 error. This issue affects the sign-up process in the production environment.

### Solution:
The root cause of the issue is a trailing slash in the Cognito callback URLs. To resolve this issue, remove the trailing slash from the Earthdata production site callback URL in the AWS Cognito configuration settings (found in the "App client settings" section). This resolves fix the 404 error and allows users to sign up successfully.

**Comment by naomatheus** [comment]
Retroactively logging this issue. Marking as resolved. 
There is a chance this is a duplicate.

**Comment by wrynearson** [comment]
FYI @bwbaker1 – this issue has been solved.

**Comment by bwbaker1** [comment]
👍
