### ISSUE TITLE
Site crashes while viewing ATBD when `document.publication_references` is empty in view mode

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#467]
_[From Slack](https://developmentseed.slack.com/archives/CG4JC6U2V/p1682319073289369)_

[This document](https://nasa-apt.surge.sh/documents/wills-test-atbd/v1.0) is no longer viewable (but is editable). The following error is displayed:
> TypeError: Cannot use ‘in’ operator to search for ‘authors’ in undefined

## Acceptance criteria

- [ ] This error is reproduced on another document
- [ ] This error is fixed

**Comment by bwbaker1** [comment]
@wrynearson status?

**Comment by wrynearson** [comment]
@bwbaker1 this has not been resolved, but we've only seen it on this individual document. I'd say this issue is "stale" because we can't reproduce it. We guess the issue came from making edits to documents and also changing the tool itself.

We can reopen the ticket if we see the same issue again.
