### ISSUE TITLE
Bug: `User not found` with newly created document

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#470]
Last week, I created the account info@developmentseed.org. Today, I went into Cognito and added the user to the `contributor` user pool.

When I create reports with the user, the author (info@developmentseed.org) is displayed as `User not found`. As you can see in the video below, sometimes the author is then found, but it reverts back to being not found when refreshing the page.

https://user-images.githubusercontent.com/25919630/235433394-d5de38de-f360-4440-9f0d-77b2c5aee86e.mov

## Acceptance Criteria

- [ ] Authors (users) are found

**Comment by wrynearson** [comment]
@kamicut I've got another frontend bug for you. Tagging @thenav56 as well because he implemented the backed changes for the "User not found" field.

**Comment by kamicut** [comment]
@wrynearson I took a quick look into this: 
1. the "User not found" string doesn't exist in the frontend, and following the code doesn't yield any error like that.
2. The shown string is supposed to be the `preferred_username` of the logged in user (`Devseed (info)`. It's strange that it's showing in the login button but not in that particular instance.

Could I have access to this particular user to test it out?

**Comment by wrynearson** [comment]
Thanks @kamicut for looking into this.

1. Is it possible that string is in the backend? @thenav56 was working on this issue.

I added you and `contributor1` as collaborators, so you should be able to [access it now](https://nasa-apt.surge.sh/documents/untitled-document-65165165134986/v1.0)

**Comment by thenav56** [comment]
@kamicut @wrynearson Yes, `User Not Found` is provided from the server side. This change was added through https://github.com/NASA-IMPACT/nasa-apt/pull/658 and https://github.com/NASA-IMPACT/nasa-apt/pull/662

This can happen when the user's id is assigned to an entity but doesn't exist in Cognito. Looking at the video above that doesn't seem to be the reason.

Is this still happening @wrynearson? It will be tricky to troubleshoot this, as we will need to add additional debug logging in the server.

I wasn't able to replicate this using https://nasa-apt.surge.sh/
