### ISSUE TITLE
Ask user for the ATBD title before creating an ATBD

### ISSUE THREAD

**Issue by sunu** [NASA-IMPACT/nasa-apt-frontend#476]
We need to prompt the user for a title before creating the ATBD. At present, the backend attempts to enforce this requirement, but the frontend sends "Untitled ATBD" as the default title.

Using "Untitled ATBD" as the default title causes issues when dispatching notifications. For more information, see https://github.com/NASA-IMPACT/nasa-apt/issues/609#issuecomment-1536018469.

To implement this, we'll need to modify the UI as well. After the user clicks the "Create ATBD" button, we can display a modal to request the text input for the title.

**Comment by wrynearson** [comment]
@sunu do you know what the status of this is? Should we work on this next sprint?

**Comment by sunu** [comment]
@wrynearson Don't think we have worked on this. As @frozenhelium is already working on modifying the ATBD creation flow for the PDF upload workflow, this issue might fit nicely into that work as well.
