### ISSUE TITLE
`Alias` field should auto-generate in PDF-mode ATBDS

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#489]
_From testing: https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/486#pullrequestreview-1456970164_

## Current Behavior

PDF-mode ATBDs do not auto-generate aliases.

## Expected Behavior

- [x] The `alias` field auto-populates based on content from the ATBD Title field

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review on staging.

**Comment by bwbaker1** [comment]
@wrynearson This works and looks good.
