### ISSUE TITLE
Block non-PDF files in PDF attachment upload process

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#491]
_From https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/486#pullrequestreview-1456970164, comment 3_

## Current Behavior

Users can upload any file in the PDF Attachment step. The file successfully uploads.

## Expected Behavior

- [ ] Only PDF files are accepted
- [ ] An error toast (with https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/490) appears if non-PDF files are attempted to be uploaded.

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review on staging.

**Comment by bwbaker1** [comment]
@wrynearson This is nice! I have a question though. Do we need an error toast if someone has an uploaded pdf and then starts to upload a file but decides to cancel the upload? See the video for more details. 

This isn't a huge deal, but it caught my attention while testing.

https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/56319064/c263a4a0-f599-465c-bae5-10b3997e75e3

**Comment by wrynearson** [comment]
Oh good catch @bwbaker1, let's see if @frozenhelium can easily change the error toast to only appear when an incorrect file is uploaded (and not when the user cancels an upload like you showed).
