### ISSUE TITLE
Remove some `steps` in PDF-mode ATBD creation workflow

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#492]
## Current Behavior

We have the same "metadata" steps from the APT-created ATBD creation workflow in the PDF-upload workflow:

<img width="341" alt="ATBD steps" src="https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/25919630/25b9dd62-314a-4d4f-ad16-9e81a0454d5b">

## Desired Behavior

- **If possible**, the PDF upload workflow should only have the following sections
    - Identifying Information
    - Contacts
    - Closeout _but only ATBD summary and Plain Language Summary_

## Acceptance Criteria

- [ ] Remove `References` step from PDF upload workflow
- [ ] Remove all fields except `ATBD Summary` and `Plain Language Summary` from the `Closeout` step from the PDF upload workflow

**Comment by bwbaker1** [comment]
@wrynearson Sorry for the misunderstanding, but let's keep the "Contacts" section. This is needed. Otherwise, the acceptance criteria is correct.

**Comment by wrynearson** [comment]
OK @bwbaker1, no problem, I edited the acceptance criteria

**Comment by wrynearson** [comment]
@bwbaker1 this is on staging and is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson This looks good - much better without the references step. 
Only one thing regarding the closeout step and that is the Keywords are now gone, which ideally we would like to keep for search purposes. Was the Keywords somehow linked to the journal details? Before, the outline was:

- short atbd summary
- plain language summary
- keywords
- Journal Details

**Comment by wrynearson** [comment]
No problem @bwbaker1, I've re-added the field. Now the closeout step in the PDF upload workflow looks like this:

<img width="1292" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/25919630/31ec22db-6fb2-4c73-992b-772e53df11db">

cc @frozenhelium

**Comment by bwbaker1** [comment]
Thanks @wrynearson!!
