### ISSUE TITLE
PDF-mode contacts section doesn’t delete

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#493]
_See [this video](https://github.com/NASA-IMPACT/nasa-apt/issues/726#issuecomment-1582582439), point 1_

## Current Behavior

When a user tries to delete a contact in the `contacts` step of the PDF upload workflow, they are unable to.

## Expected Behavior

- [ ] Users are able to delete contact info in the `contacts` step

**Comment by frozenhelium** [comment]
@wrynearson This is fixed in the staging now

**Comment by wrynearson** [comment]
Thanks @frozenhelium, @bwbaker1 this is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson This is great! I think we can call this ready for production.
