### ISSUE TITLE
Document Status tracker doesn't update properly in PDF-mode documents

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#494]
_See [this video](https://github.com/NASA-IMPACT/nasa-apt/issues/726#issuecomment-1582582439), point 2_

## Current Behavior

When a user updates the status of a section in the `Contacts` or `Attachments` steps, the document progress tracker updates incorrectly (e.g., the progress _decreases_ when a section is marked as `complete`). 

## Expected Behavior

- [ ] PDF-mode section status updates have correct document status calculations

**Comment by wrynearson** [comment]
@bwbaker1 this is on staging and is ready for your review

**Comment by frozenhelium** [comment]
@wrynearson looks like I missed something in the Close out section, so at the moment, it shows only 63% complete. The previous issue is fixed. I'll send the fix for this one as well.

**Comment by bwbaker1** [comment]
@wrynearson This looks good, and I think its ready for prod. 
thanks @frozenhelium!
