### ISSUE TITLE
Link `Download` button to uploaded PDF in PDF-mode documents

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#495]
_See [this video](https://github.com/NASA-IMPACT/nasa-apt/issues/726#issuecomment-1582582439), point 3_

## Current Behavior

When users try to download a PDF-type document, APT tries to generate and serve a PDF as is done for the APT-created couments

## Expected Behavior

- [ ] Users are served the uploaded document

**Comment by sunu** [comment]
@kamicut https://github.com/NASA-IMPACT/nasa-apt/pull/755 fixes this issue by returning the s3 url for the uploaded pdf when a pdf export is requested through the api. But I think on the frontend, the s3 url is already available (through `version.pdf.file_path`) when showing a PDF ATBD version. So we can connect the download button directly to that existing url and avoid making the API call for PDF ATBDs.

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for you to test on staging

**Comment by bwbaker1** [comment]
@wrynearson I'm not getting any errors, but PDFs aren't downloading from the search interface. I've tested different ATBDs, browsers, etc., but nothing happens. I just get the "Downloading PDF...." toast

<img width="1535" alt="Screen Shot 2023-06-19 at 6 53 21 AM" src="https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/56319064/50f99105-5d32-4d81-b2d9-1f212e532939">

**Comment by wrynearson** [comment]
Oh thanks for flagging this. The document I tested this on worked. 

@frozenhelium could you look into this?

**Comment by sunu** [comment]
@frozenhelium imo, we should request the file directly from s3 from the frontend without calling the export endpoint for PDF ATBDs (see https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/495#issuecomment-1591015269)

**Comment by frozenhelium** [comment]
@sunu sure, I'll update it accordingly

**Comment by wrynearson** [comment]
@bwbaker1 please go ahead and test this again when you have the chance.
