### ISSUE TITLE
Replace toggle with buttons in `Create ATBD` modal

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#496]
## Current Behavior

We have a toggle, that users can turn on to activate PDF-upload mode.

## Desired Behavior

![image](https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/25919630/a1cb2d14-c010-4773-b83a-4b3eb2b1b4d7)

- [ ] Two buttons let users choose which ATBD workflow mode they prefer to use (APT-created or PDF-upload)
- [ ] Include tooltip to help users decide between the two options

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for you to test on staging. We went with a slightly different design than what you suggested. Let me know what you think. If you'd prefer your design, we can change it easily.

<img width="847" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/25919630/9b053466-7091-4b18-bb6f-ae11d20e0ec5">

**Comment by bwbaker1** [comment]
@wrynearson Nice! This works great. I especially like the tooltip on the Upload existing button.
