### ISSUE TITLE
Create new section in `Contacts` step for Reviewer Information, rename to `Contacts and Reviewer Information`

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#514]
_See https://github.com/NASA-IMPACT/nasa-apt/issues/753#issuecomment-1600820097 and previous comments for context_

## Current Behavior

Currently, all reviews are conducted in APT through a dedicated review process. However, some historical ATBDs (PDF uploads) will have their content reviewed before entering in APT, or reviewed by people who don't have APT accounts.

## Desired Behavior

Basic reviewer metadata is captured for _all_ ATBDs (APT or PDF workflow).

## Acceptance Criteria

<img width="1232" alt="image" src="https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/25919630/7b4d60f5-06e5-4967-b69d-62ab83cd126c">

- [ ] In the `Contacts` step, add a similar field below where users can add reviewer information.
- [ ] ~~First, add a checkbox/yes-no select with the prompt `Has this ATBD been reviewed already?`~~
    - [ ] ~~If yes,~~ reveal the reviewer info collection form (https://github.com/NASA-IMPACT/nasa-apt/issues/753)
    - [ ] ~~If no, do nothing (this will be reviewed in the platform)~~
- [ ] Rename step to `Contacts and Reviewer Information` 
- [ ] This new section (reviewer info) should only be visible in the _edit_ mode, not _view_ or _pdf exports_

**Comment by wrynearson** [comment]
@bwbaker1, do you see any usability issues when users fill in reviewer information before writing their ATBD? Do users know who will review their ATBD? I thought that the review step was somewhat anonymized.

**Comment by bwbaker1** [comment]
@wrynearson I don't see any issues with adding the reviewers first. Users can always come back and edit this section later if needed.  
I think the initial conceptualization was that the review process would be anonymous, but this isn't really the case. Each science team has specific people that will review the ATBD. There is still anonymity in that the users do not know the specific person leaving reviews (i.e., they see reviewer1, reviewer2, etc. on the comments).

**Comment by wrynearson** [comment]
@bwbaker1 this is ready for your review

**Comment by bwbaker1** [comment]
@wrynearson Looks good to me. I think it is ready for prod.

**Comment by bwbaker1** [comment]
@wrynearson i think this is ready for prod. Just see my comments related [permissions ](https://github.com/orgs/NASA-IMPACT/projects/13/views/1?pane=issue&itemId=31562118#:~:text=%40wrynearson%20My-,thinking,-was%20that%20the).
