### ISSUE TITLE
Add radio select for journal submission to PDF upload closeout section

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#515]
## Current Behavior

We collect 3 fields of information in the `Closeout` section of ATBDs uploaded as PDFs

## Desired Behavior

We add a 4th field, below `Keywords`, that has a _similar_ layout and function as the `Journal Details` section in the APT-created ATBD workflow.

<img width="1356" alt="Journal info" src="https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/25919630/cf9915a6-d1bc-4b21-9842-051650d83be8">

## Acceptance Criteria

- [x] New section is added to PDF-upload workflow in the `Closeout` step
- [x] _The radio buttons don't need to reveal any additional fields like they do in the APT-creation mode_. This is just to capture the state of the journal submission process, not additional information.

**Comment by bwbaker1** [comment]
@wrynearson That's exactly what we need. Thanks!

**Comment by bwbaker1** [comment]
@wrynearson This looks good.
