### ISSUE TITLE
Change instructions for citations

### ISSUE THREAD

**Issue by wrynearson** [NASA-IMPACT/nasa-apt-frontend#580]
Currently, we instruct users to input names as `Firstname Lastname _and_` for the citations (in Identifying Information) but `Lastname, Firstname _and_` for the references.

![image](https://github.com/NASA-IMPACT/nasa-apt-frontend/assets/719357/5e4c8abe-74f2-4e8d-a2ee-a61db407d6de)

We should change the citations field instructions to match the references.

This relates to https://github.com/NASA-IMPACT/nasa-apt/issues/825 cc @bwbaker1

**Comment by kamicut** [comment]
https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/581 uses the `formatAuthors` code to format the authors. We should keep the input consistent for authors across the app.
